image: awhalen/docker-php-composer-node

cache:
  key: "SystemManager-Core"
  paths:
    - "node_modules/"


stages:
  - Build
  - TestCore
  - TestWorker

build_core:
  stage: Build
  script:
    - cd core/
    - yarn && yarn build
  artifacts:
    paths:
      - './core/build'


build_worker:
  stage: Build
  script:
    - cd worker/
    - yarn && yarn build
  artifacts:
    paths:
      - './worker/build'

test_core:
  stage: TestCore
  script:
    - echo "No tests are defined yet"


test_worker:
  stage: TestWorker
  script:
    - echo "No tests are defined yet"

