image: awhalen/docker-php-composer-node

cache:
  key: "SystemManager-Core"
  paths:
    - "node_modules/"


stages:
  - build_core
  - build_worker
  - test_core
  - test_worker

build_core:
  stage: build_core
  script:
    - cd core/
    - yarn && yarn build
  artifacts:
    paths:
      - './core/build'
      - './worker/build'

test_core:
  stage: test_core
  script:
    - echo "No tests are defined yet"


build_worker:
  stage: build_worker
  script:
    - cd worker/
    - yarn && yarn build
  artifacts:
    paths:
      - './core/build'
      - './worker/build'

test_worker:
  stage: test_worker
  script:
    - echo "No tests are defined yet"

