image: awhalen/docker-php-composer-node

cache:
  key: "SystemManager-Core"
  paths:
    - "node_modules/"


stages:
  - core
  - worker

build_core:
  stage: core
  script:
    - cd core/
    - yarn && yarn build
  artifacts:
    paths:
      - './core/build'
      - './worker/build'

test_core:
  stage: core
  script:
    - echo "No tests are defined yet"


build_worker:
  stage: worker
  script:
    - cd worker/
    - yarn && yarn build
  artifacts:
    paths:
      - './core/build'
      - './worker/build'

test_worker:
  stage: worker
  script:
    - echo "No tests are defined yet"

