image: awhalen/docker-php-composer-node

cache:
  key: "SystemManager-Core"
  paths:
    - "core/node_modules/"
    - "worker/node_modules/"


stages:
  - Build
  - Test

build_core:
  stage: Build
  script:
    - cd core/
    - npm install && npm run build
  artifacts:
    paths:
      - './core/build'


build_worker:
  stage: Build
  script:
    - cd worker/
    - npm install && npm run build
  artifacts:
    paths:
      - './worker/build'

test_core:
  stage: Test
  needs:
    - build_core
  script:
    - echo "No tests are defined yet"


test_worker:
  stage: Test
  needs:
    - build_worker
  script:
    - echo "No tests are defined yet"

