image: awhalen/docker-php-composer-node

cache:
  key: "SystemManager-Core"
  paths:
    - "node_modules/"


stages:
  - build
  - test_core
  - test_worker

build_core:
  stage: build
  script:
    - cd core/
    - yarn && yarn build
  artifacts:
    paths:
      - './core/build'


build_worker:
  stage: build
  script:
    - cd worker/
    - yarn && yarn build
  artifacts:
    paths:
      - './worker/build'

test_core:
  stage: test
  needs:
    - build_core
  script:
    - echo "No tests are defined yet"


test_worker:
  stage: test
  needs:
    - build_worker
  script:
    - echo "No tests are defined yet"

