const errorName = {
    NOTFOUND: "NOTFOUND",
    INTERNALERROR: "INTERNALERROR",

    NOPASSWORDMATCH: "NOPASSWORDMATCH",
    USERALREADYEXISTS: "USERALREADYEXISTS",

    NOPERMISSION: "NOPERMISSION",
}

export default errorName