const errorName = {
    NOTFOUND: "NOTFOUND",
    INTERNALERROR: "INTERNALERROR",

    NOPASSWORDMATCH: "NOPASSWORDMATCH",
    USERALREADYEXISTS: "USERALREADYEXISTS",

    NOPERMISSION: "NOPERMISSION",

    FAILEDTOSENDCOMMAND: "FAILEDTOSENDCOMMAND",

    ARANGODBERROR: "ARANGODBERROR"
};

export default errorName;