const errorName = {
    NOTFOUND: "NOTFOUND",
    INTERNALERROR: "INTERNALERROR",

    NOPASSWORDMATCH: "NOPASSWORDMATCH",
    USERALREADYEXISTS: "USERALREADYEXISTS",

    NOPERMISSION: "NOPERMISSION",

    FAILEDTOSENDCOMMAND: "FAILEDTOSENDCOMMAND"
};

export default errorName;